name: Test
on:
  push:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
    test:
      runs-on: ubuntu-latest
      env:
        PGHOST: "localhost"
        PGUSER: "postgres"
        PGPORT: "5432"
        PGPASSWORD: "postgres"
      steps:
      - uses: actions/checkout@v1
      - name: Build the docker-compose stack
        run: docker compose -f docker-compose.yml up -d
      - name: Check running containers
        run: docker ps -a
      - name: Set up library
        run: ./scripts/setup-lib.sh
      - name: Set up testing data
        run: ./scripts/setup-testdata.sh
      - name: Install test dependencies
        run: npm ci
        working-directory: ./test
      - name: Run Jest tests
        run: npm run test --ci --reporters=default --reporters=jest-junit .
        working-directory: ./test
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: ${{ !cancelled() }}       # run this step even if previous step failed
        with:
          name: JEST Tests
          path: test/output/junit.xml
          reporter: jest-junit
      - name: Run performance test
        run: ./scripts/test-perf.sh

